import random

motivational_quotes = [
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Believe you can and you're halfway there.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "You miss 100 percent of the shots you don't take.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "You are never too old to set another goal or to dream a new dream.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Do something today that your future self will thank you for.",
    "Happiness can be found even in the darkest of times if one only remembers to turn on the light.",
    "You don't have to be great to start, but you have to start to be great.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "The best way to predict your future is to create it.",
    "You are the architect of your own destiny; build wisely.",
    "The biggest risk is not taking any risk.",
    "You don't have to be perfect to be amazing.",
    "The only person you should try to be better than is the person you were yesterday.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "You are stronger than you seem, braver than you believe, and smarter than you think.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You are capable of amazing things.",
    "The only way to do great work is to love what you do.",
    "The biggest risk is not taking any risk.",
    "You are the architect of your own destiny; build wisely.",
    "The only way to achieve the impossible is to believe it is possible."
]

encouragement_messages = [
    "Wishing you a great day ahead!",
    "Keep up the good work!",
    "You're doing great, keep pushing forward!",
    "Good luck with your endeavors!",
    "You're on a roll, keep it up!"
]

while True:
    user_feeling = input("How are you feeling today? (unmotivated or motivated TYPE EXIT TO EXIT THE PROGRAM)  ")
    if user_feeling.lower().strip() in ['unmotivated', 'down', 'low', 'demotivated']:
        quote = random.choice(motivational_quotes)
        print(quote)
    elif user_feeling.lower().strip() == 'motivated':
        message = random.choice(encouragement_messages)
        print(message)
    elif user_feeling.lower().strip() == 'exit':
        print("Exiting the program. Have a great day!")
        break
    else:
        print("Let's try again when you're ready.")
